services:
  mongodb:
    image : mongo:3.4.3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./MapService/mongodb/database:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - mongodb_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  mongodb_network:
    name: mongodb_network
