version: "2.3"
services:
  mongodb:
    build: .
    platform: linux/amd64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 127.0.0.1:27017:27017  # expose db to localhost
    networks:
      - mongodb_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 5
networks:
  mongodb_network:
    name: mongodb_network